#!/usr/bin/env python3
"""Regenerate app/jni/src/src/ss_cjk_data.h, the bottom-screen CJK glyph atlas.

The bottom screen draws Simplified Chinese from a tiny baked atlas instead of a
runtime font: every character used by the bottom-screen UI is rendered once from
Fusion Pixel's native 10px bitmap face into a 16x16 cell and stored as 2bpp
(0 = transparent, 1 = outline, 2 = body), 4 bytes per row, 64 bytes per glyph.
second_screen.c (3DS/Citro) and second_screen_sdl.c (desktop preview) both blit
that atlas, so the two stay pixel-identical.

Usage:
    gen_cjk_atlas.py [--font PATH] [--check]

    --font   10px bitmap face to render with.  Defaults to
             fonts/fusion-pixel-10px-monospaced-zh_hans.ms.bitmap.ttf, taken
             from TakWolf/fusion-pixel-font release 2026.08.11:
             fusion-pixel-font-10px-monospaced-ms.bitmap.ttf-v2026.08.11.zip
    --check  only report whether ss_cjk_data.h is up to date; write nothing.

The character set is discovered by scanning the bottom-screen sources for CJK
codepoints, so adding a Chinese string to the UI only requires re-running this
script.
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "app", "jni", "src", "src", "ss_cjk_data.h")
DEFAULT_FONT = os.path.join(
    ROOT, "fonts", "fusion-pixel-10px-monospaced-zh_hans.ms.bitmap.ttf")
SOURCES = [
    "app/jni/src/src/platform/linux/second_screen_sdl.c",
    "app/jni/src/src/second_screen.c",
    # Updater status messages, shown on the bottom screen's UPDATE panel.
    "platform/3ds/source/updater.c",
]

# Rendering parameters.  The 10px face draws into a 10x10 box; the box is blitted
# at (3, 2) inside the 16x16 cell, which is what the draw code compensates for
# with its `y - 4 * scale` baseline shift.
CELL = 16
BOX = 10
OFF_X = 3
OFF_Y = 2
BODY = 2
OUTLINE = 1


def is_cjk(ch):
    return ("\u4e00" <= ch <= "\u9fff" or "\u3000" <= ch <= "\u303f"
            or "\uff00" <= ch <= "\uffef")


def used_chars():
    seen = set()
    for rel in SOURCES:
        with open(os.path.join(ROOT, rel), encoding="utf-8", errors="replace") as fh:
            seen.update(ch for ch in fh.read() if is_cjk(ch))
    return sorted(seen)


def render(font, ch):
    from PIL import Image, ImageDraw
    img = Image.new("L", (CELL, CELL), 0)
    ImageDraw.Draw(img).text((OFF_X, OFF_Y), ch, font=font, fill=255)
    px = img.load()
    out = bytearray(CELL * 4)
    for y in range(CELL):
        for x in range(CELL):
            v = px[x, y]
            if v <= 0:
                continue
            out[y * 4 + x // 4] |= (BODY if v >= 128 else OUTLINE) << ((3 - (x % 4)) * 2)
    return bytes(out)


def c_escape(data):
    parts = []
    for b in data:
        if b == 0x22:
            parts.append('\\"')
        elif b == 0x5C:
            parts.append("\\\\")
        elif 0x20 <= b < 0x7F:
            parts.append(chr(b))
        else:
            parts.append("\\x%02x" % b)
    return "".join(parts)


def build(font_path):
    from PIL import ImageFont
    chars = used_chars()
    font = ImageFont.truetype(font_path, BOX)
    glyphs = [render(font, ch) for ch in chars]

    lines = [
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "// Bottom-screen Simplified-Chinese glyph atlas, NATIVE 10px Fusion Pixel bitmap"
        " (crisp), no outline.",
        "// 16x16 2bpp cell (0=transparent,2=white body), centered 10px glyph,"
        " one per char in kSSCjkChars order.",
        "// Generated by tools/secondscreen/gen_cjk_atlas.py -- do not edit by hand.",
        "enum { kSSCjkCount = %d };" % len(chars),
        'static const char kSSCjkChars[kSSCjkCount*4+1] = "%s";'
        % c_escape("".join(chars).encode("utf-8")),
        "static const uint8_t kSSCjkGlyphs[kSSCjkCount*64] = {",
    ]
    for g in glyphs:
        lines.append("  " + ", ".join("0x%02x" % b for b in g) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n", chars, glyphs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.font):
        sys.exit("font not found: %s\nsee the module docstring for the download URL"
                 % args.font)
    text, chars, _ = build(args.font)
    current = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as fh:
            current = fh.read()

    if args.check:
        if current == text:
            print("ss_cjk_data.h is up to date (%d glyphs)" % len(chars))
            return 0
        old = re.search(r"kSSCjkCount = (\d+)", current or "")
        print("ss_cjk_data.h is OUT OF DATE (have %s, need %d glyphs)"
              % (old.group(1) if old else "?", len(chars)))
        return 1

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d glyphs)" % (os.path.relpath(OUT, ROOT), len(chars)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
