#!/usr/bin/env python3
# Bakes a small anti-aliased triangle mask (white RGB, real alpha) used to
# draw the title/cinema-screen triforce in second_screen_sdl.c via tinted
# texture blits, replacing the old per-scanline tri_up() rasterizer. The
# shape is procedural (not sourced from a ROM or existing artwork), rendered
# supersampled and downsampled for antialiasing, matching the equilateral
# proportions the previous code used (slope ~= tan(30 deg) = 0.5774).
#
# Needs Pillow. Run from repo root:
#   python tools/secondscreen/gen_triforce.py
# The generated header is committed, so a normal build does not need to run
# this -- only re-run it if you want to change the triangle's shape/size.
import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "app", "jni", "src", "src", "platform", "linux")

SUPERSAMPLE = 512  # render large, then downsample for antialiasing
FINAL = 64          # baked texture size (same ballpark as ss_textures.h tiles)
# Small margin only to keep the supersampled polygon off the canvas edge;
# callers can treat the baked texture as ~tight to the triangle's bounds.
MARGIN = SUPERSAMPLE * 0.015


def gen_triforce_mask():
    img = Image.new("RGBA", (SUPERSAMPLE, SUPERSAMPLE), (255, 255, 255, 0))
    draw = ImageDraw.Draw(img)

    top = MARGIN
    bottom = SUPERSAMPLE - MARGIN
    apex_x = SUPERSAMPLE / 2.0
    half_w = (bottom - top) * 0.5774  # equilateral, matches old tri_up() slope

    pts = [
        (apex_x, top),               # apex
        (apex_x - half_w, bottom),   # base-left
        (apex_x + half_w, bottom),   # base-right
    ]
    draw.polygon(pts, fill=(255, 255, 255, 255))
    return img.resize((FINAL, FINAL), Image.LANCZOS)


def write_header(img):
    w, h = img.size
    px = list(img.getdata())
    # White RGB + real alpha: SDL_SetTextureColorMod multiplies the stored
    # RGB by the tint color, so keeping RGB at 0xffffff means the on-screen
    # color is exactly whatever tint is applied at draw time (matches the
    # old code's COL(g, g*0.83, g*0.41) pulse).
    vals = [f"0x{a:02x}ffffff" for (r, g, b, a) in px]
    rows = [",".join(vals[i:i + 12]) for i in range(0, len(vals), 12)]
    out = [
        "// Anti-aliased upward-triangle mask (white RGB, real alpha) used to",
        "// draw the title/cinema-screen triforce via tinted texture blits",
        "// instead of the old per-scanline tri_up() rasterizer. Generated by",
        "// tools/secondscreen/gen_triforce.py -- do not hand-edit.",
        "#pragma once",
        "",
        f"#define kSSTexTriforce_W {w}",
        f"#define kSSTexTriforce_H {h}",
        f"static const unsigned int kSSTexTriforce[{w * h}] = {{",
        ",\n".join(rows),
        "};",
    ]
    open(os.path.join(SRC, "ss_tex_triforce.h"), "w", newline="\n").write(
        "\n".join(out) + "\n")
    print("wrote src/ss_tex_triforce.h")


if __name__ == "__main__":
    write_header(gen_triforce_mask())
